### ISSUE TITLE
Module not found error.

### ISSUE THREAD

**Issue by mandapati7** [jshttp/mime-types#71] opened 2020-01-22 16:12 UTC
Hi,

I have included mime-types in my angular projects and when I have build the project it is throwing the below error.

[ERROR] 
[ERROR] ERROR in ./node_modules/mime-types/index.js
**[ERROR] Module not found: Error: Can't resolve 'path' in '/var/XXX/jenkins/972a015a/workspace/EW-3531535_oce_irs_app_ci_master/oce_irs_web/node_modules/mime-types'**
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! oce-irs-web@0.0.0 build-prod: `ng build --prod`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the oce-irs-web@0.0.0 build-prod script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /opt/jenkins/.npm/_logs/2020-01-22T15_32_27_448Z-debug.log

**Comment by dougwilson** [comment] 2020-01-22 16:31
Duplicate of #69

**Closed by dougwilson** 2020-01-22 16:31 UTC
